/* http://www.cs.man.ac.uk/~pjj/bnf/bnf.html */

digit ::= '1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'

natural ::= digit+ ('0'|digit)*

Sign ::= '+' | '-'

Rational ::= Sign? natural ('/' natural)?

SRational ::= Sign natural ('/' natural)?

Exp ::= natural | Rational

ExpRational ::= (Rational | '(' Rational ')') ('^' (Rational | '(' Rational ')'))?

SExpRational ::= (SRational | '(' SRational ')') ('^' (Rational | '(' Rational ')'))?

i ::= 'i' | '𝑖' | '𝒾' | '𝓲' | 'ⅈ'

Complex ::= (ExpRational SExpRational i) | ExpRational | (ExpRational i) | (Sign? i)

SComplex ::= (SExpRational SExpRational i) | SExpRational | (SExpRational i) | (Sign i)

charlit ::= gcharl | gcharL | charl | charL

Literal ::= charlit ('_' natural)?

ExpLiteral ::= Literal ('^' (Rational | '(' Rational ')'))?

Monomial ::= Complex ExpLiteral*

SMonomial ::= SComplex ExpLiteral*

Polynomial ::= Monomial SMonomial*